artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion      #the root directory folder will be created which has data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip  #this is source it can be a database, website or api
  local_data_file: artifacts/data_ingestion/data.zip    #, path for zip file to be downloaded
  unzip_dir: artifacts/data_ingestion   #this is path where you will unzip the data


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  
  
  #joblib save the model in the form of file 

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib  
  metric_file_name: artifacts/model_evaluation/metrics.json